version: '3.8'

services:
  web:
    build:
      context: ./flask
    ports:
      - 9000:9000
    volumes:
      - ./flask:/workspace/flask
    networks:
      - proxy
      - database
    container_name: trip

  nginx:
    build:
      context: ./nginx
    restart: always
    depends_on:
      - web
    volumes:
      - ./flask:/workspace/flask
      - /var/log/trip_web:/var/log/nginx
    networks:
      - proxy
    environment:
      - VIRTUAL_HOST=trip.taipeilife.site
      - LETSENCRYPT_HOST=trip.taipeilife.site
    container_name: proxied-trip

networks:
  proxy:
    external: true
    name: self-nginx-proxy

  database:
    external: true
    name: self-mysql
