version: '3.8'

services:
 web:
  build:
   context: ./flask
  ports:
    - 9000:9000
  volumes:
    - ./flask:/workspace/flask
  depends_on:
    mysqldb:
      condition: service_healthy
  container_name: trip

 mysqldb:
  image: mysql
  ports:
    - 53306:3306
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: taipeitrip
  healthcheck:
    test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    timeout: 10s
    retries: 5
  volumes:
    - mysql:/var/lib/mysql
    - mysql_config:/etc/mysql
  container_name: db_trip

volumes:
  mysql:
  mysql_config: