version: '3.8'
name: mysql_db
services:
  mysqldb:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
      - ./dbinit:/docker-entrypoint-initdb.d
    networks:
      - database
    container_name: db

volumes:
  mysql:
  mysql_config:

networks:
  database:
    name: self-mysql
