name: Taipei Trip CI/CD

# control the flow
on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    steps:
      - name: Check the files
        uses: actions/checkout@v3
    
      - name: Build the .env file for Flask application
        run: |
          cd flask/app/
          echo "${{ secrets.ENV_FILE }}" > .env
          
      - name: Build Docker network for next step use
        run: |
          docker network create self-nginx-proxy
          
      - name: Run Docker Compose to start MySQL for Taipei Trip website
        run: |
          docker compose -f docker-compose-db-forCI.yml up -d
      
      - name: Run Docker Compose to start Taipei Trip website
        run: |
          docker compose up --build -d
